import {
    SonuNigam,
    Shreya,
    RagaRockers,
    Samay,
    Shudharani,
    DJArjun,
    Nakul,
    Rishabh,
    SoulStringBand,
    TheRustam,
    DJNisha,
    MagicMan,
    RitikaKapoor,
    DJZeeshan,
    VishalMishra
} from "../assets/artistsImages"

export const dummyArtists = [
  {
    id: "1",
    name: "Shreya Ghoshal",
    bio: "Award-winning playback singer with a career spanning over two decades. Performs live for weddings, corporate events, and music festivals across India.",
    category: ["Singer", "Bollywood"],
    languages: ["Hindi", "Bengali", "Tamil", "Telugu"],
    priceRange: "2,00,000 - 5,00,000",
    location: "Mumbai, Maharashtra",
    rating: 4.9,
    image: Shreya,
    email: "shreya@example.com",
    phone: "+91-9876543210",
  },
  {
  id: "2",
  name: "Sonu Nigam",
  bio: "Legendary playback singer with a career spanning over three decades. Known for his versatile voice and live stage presence. Performs at weddings, concerts, corporate shows, and cultural festivals.",
  category: ["Singer", "Bollywood"],
  languages: ["Hindi", "Kannada", "Bengali", "Marathi", "Tamil", "Telugu", "English"],
  priceRange: "5,00,000 - 12,00,000",
  location: "Mumbai, Maharashtra",
  rating: 5.0,
  image: SonuNigam,
  email: "sonu@example.com",
  phone: "+91-9876543211",
}
,
  {
    id: "3",
    name: "Raga Rockers",
    bio: "Fusion rock band blending Indian classical instruments with Western rock. Popular at college fests, concerts, and destination weddings.",
    category: ["Band", "Fusion"],
    languages: ["Hindi", "English"],
    priceRange: "3,00,000 - 6,00,000",
    location: "Bangalore, Karnataka",
    rating: 4.7,
    image: RagaRockers,
    email: "ragarockers@example.com",
    phone: "+91-9876543212",
  },
  {
    id: "4",
    name: "DJ Arjun",
    bio: "Top-rated Bollywood DJ known for high-energy club gigs and destination weddings. Offers a full sound and lighting setup.",
    category: ["DJ", "Bollywood"],
    languages: ["Hindi", "English"],
    priceRange: "1,50,000 - 3,00,000",
    location: "Pune, Maharashtra",
    rating: 4.9,
    image: DJArjun,
    email: "arjun@example.com",
    phone: "+91-9876543213",
  },
  {
  id: "5",
  name: "Rishabh Sharma",
  bio: "Award-winning sitar maestro trained under Pt. Ravi Shankar lineage. Performs at classical concerts, corporate evenings, and temple festivals.",
  category: ["Musician", "Classical"],
  languages: ["Hindi", "English"],
  priceRange: "1,00,000 - 2,00,000",
  location: "Varanasi, Uttar Pradesh",
  rating: 4.9,
  image: Rishabh,
  email: "rishabh@example.com",
  phone: "+91-9876543214",
},
{
  id: "6",
  name: "Samay Raina",
  bio: "Stand-up comedian and YouTube sensation known for sharp wit and observational humor. Performs at festivals, private events, and comedy clubs.",
  category: ["Comedian", "Entertainer"],
  languages: ["Hindi", "English"],
  priceRange: "2,00,000 - 4,00,000",
  location: "Mumbai, Maharashtra",
  rating: 4.8,
  image: Samay,
  email: "samay@example.com",
  phone: "+91-9876543215",
},
{
  id: "7",
  name: "Shudharani Jadhav",
  bio: "Acclaimed Bharatanatyam dancer with over 15 years of experience. Delivers powerful solo and troupe-based performances across cultural platforms.",
  category: ["Dancer", "Cultural"],
  languages: ["Marathi", "Hindi", "English"],
  priceRange: "1,50,000 - 3,00,000",
  location: "Pune, Maharashtra",
  rating: 4.9,
  image: Shudharani,
  email: "shudharani@example.com",
  phone: "+91-9876543216",
},
{
  id: "8",
  name: "Nakul Shenoy",
  bio: "Internationally acclaimed mentalist and magician known for mind-reading, illusions, and corporate performances. Regularly features at high-profile events and conferences.",
  category: ["Magician", "Mentalist"],
  languages: ["English", "Hindi", "Kannada"],
  priceRange: "2,00,000 - 4,50,000",
  location: "Bengaluru, Karnataka",
  rating: 4.9,
  image: Nakul,
  email: "nakul@example.com",
  phone: "+91-9876543217",
},
  {
    id: "9",
    name: "The Rustoms",
    bio: "Acoustic band performing unplugged Bollywood and indie tracks. Ideal for weddings, lounges, and intimate events.",
    category: ["Band", "Acoustic"],
    languages: ["Hindi", "English"],
    priceRange: "75,000 - 1,50,000",
    location: "Kolkata, West Bengal",
    rating: 4.7,
    image: TheRustam,
    email: "rustoms@example.com",
    phone: "+91-9876543218",
  },
  {
    id: "10",
    name: "DJ Nisha Beats",
    bio: "Versatile female DJ spinning Bollywood, EDM, and regional mixes. Popular in weddings, mehendi functions, and fashion events.",
    category: ["DJ", "EDM"],
    languages: ["Hindi", "English", "Punjabi"],
    priceRange: "1,00,000 - 2,50,000",
    location: "Chandigarh",
    rating: 4.8,
    image: DJNisha,
    email: "nisha@example.com",
    phone: "+91-9876543219",
  },
  {
    id: "11",
    name: "Ritika Kapoor",
    bio: "Award-winning Kathak dancer known for expressive storytelling and graceful performances. Performs at weddings, cultural nights, and school functions.",
    category: ["Dancer", "Cultural"],
    languages: ["Hindi", "English"],
    priceRange: "90,000 - 1,80,000",
    location: "Lucknow, Uttar Pradesh",
    rating: 4.8,
    image: RitikaKapoor,
    email: "ritika@example.com",
    phone: "+91-9876543220",
  },
  {
    id: "12",
    name: "DJ Zeeshan",
    bio: "Specializes in Sufi, Bollywood, and electronic sets. Regular performer at Delhi clubs and private wedding functions.",
    category: ["DJ", "Sufi"],
    languages: ["Hindi", "English", "Urdu"],
    priceRange: "1,00,000 - 2,00,000",
    location: "Delhi, NCR",
    rating: 4.7,
    image: DJZeeshan,
    email: "zeeshan@example.com",
    phone: "+91-9876543221",
  },
  {
    id: "13",
    name: "Soul Strings Band",
    bio: "Live acoustic trio that blends Hindi indie with unplugged Bollywood. Perfect for mehendi, receptions, and romantic dinners.",
    category: ["Band", "Indie"],
    languages: ["Hindi", "English"],
    priceRange: "85,000 - 1,50,000",
    location: "Hyderabad, Telangana",
    rating: 4.9,
    image: SoulStringBand,
    email: "soulstrings@example.com",
    phone: "+91-9876543222",
  },
  {
  id: "14",
  name: "Vishal Mishra",
  bio: "Bollywood playback singer and composer known for soulful ballads like 'Kaise Hua' and 'Phir Bhi Tumko Chaahunga'. Performs live at concerts, weddings, and corporate shows.",
  category: ["Singer", "Bollywood"],
  languages: ["Hindi", "English"],
  priceRange: "3,00,000 - 6,00,000",
  location: "Mumbai, Maharashtra",
  rating: 4.8,
  image: VishalMishra,
  email: "vishal@example.com",
  phone: "+91-9876543223",
},

  {
    id: "15",
    name: "MagicMan Arvind",
    bio: "Sleight-of-hand illusionist popular in school events, birthday parties, and mall shows. Also conducts educational magic workshops.",
    category: ["Magician", "Kids"],
    languages: ["Hindi", "English"],
    priceRange: "40,000 - 80,000",
    location: "Nagpur, Maharashtra",
    rating: 4.5,
    image: MagicMan,
    email: "arvind@example.com",
    phone: "+91-9876543224",
  }
];

export const dummyBookingRequests = [
  {
    id: "1",
    clientName: "Ankit Verma",
    artistName: "Shreya Ghoshal",
    eventDate: "2024-12-10",
    eventType: "Sangeet Night",
    budget: "₹3,50,000",
    status: "pending",
    requestDate: "2024-06-20",
  },
  {
    id: "2",
    clientName: "Infosys Ltd.",
    artistName: "DJ Arjun",
    eventDate: "2024-11-22",
    eventType: "Corporate Party",
    budget: "₹2,00,000",
    status: "confirmed",
    requestDate: "2024-06-18",
  },
  {
    id: "3",
    clientName: "Rohit Shetty",
    artistName: "Raga Rockers",
    eventDate: "2024-12-01",
    eventType: "Birthday Bash",
    budget: "₹4,00,000",
    status: "pending",
    requestDate: "2024-06-22",
  },
  {
    id: "4",
    clientName: "Priya Malhotra",
    artistName: "Ananya Rao",
    eventDate: "2024-10-18",
    eventType: "Wedding Ceremony",
    budget: "₹1,00,000",
    status: "rejected",
    requestDate: "2024-06-15",
  },
  {
    id: "5",
    clientName: "Tata Consultancy Services",
    artistName: "Rajiv Mehta",
    eventDate: "2024-09-15",
    eventType: "Team Retreat",
    budget: "₹1,50,000",
    status: "confirmed",
    requestDate: "2024-06-25",
  },
  {
    id: "6",
    clientName: "Indian Cultural Forum",
    artistName: "Meenakshi Iyer",
    eventDate: "2024-10-05",
    eventType: "Navratri Celebration",
    budget: "₹1,20,000",
    status: "pending",
    requestDate: "2024-06-28",
  },
  {
    id: "7",
    clientName: "Ravindra Joshi",
    artistName: "Ritika Kapoor",
    eventDate: "2024-11-09",
    eventType: "Cultural Night",
    budget: "₹1,20,000",
    status: "pending",
    requestDate: "2024-07-01",
  },
  {
    id: "8",
    clientName: "The Wedding Co.",
    artistName: "Soul Strings Band",
    eventDate: "2024-12-18",
    eventType: "Wedding Reception",
    budget: "₹1,40,000",
    status: "confirmed",
    requestDate: "2024-07-02",
  },
  {
    id: "9",
    clientName: "Sneha Arora",
    artistName: "Tanvi Mishra",
    eventDate: "2024-09-28",
    eventType: "Engagement Party",
    budget: "₹80,000",
    status: "confirmed",
    requestDate: "2024-07-03",
  },
  {
    id: "10",
    clientName: "Fun Fiesta Events",
    artistName: "MagicMan Arvind",
    eventDate: "2024-08-12",
    eventType: "Kids Birthday",
    budget: "₹50,000",
    status: "pending",
    requestDate: "2024-07-04",
  }
];
